//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Northern_Lights_Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public int IDAdmission { get; set; }
        public Nullable<bool> chirurgieProgramme { get; set; }
        public Nullable<System.DateTime> dateAdmission { get; set; }
        public Nullable<System.DateTime> dateChirurgie { get; set; }
        public Nullable<System.DateTime> dateConge { get; set; }
        public Nullable<bool> televiseur { get; set; }
        public Nullable<bool> telephone { get; set; }
        public string NSS { get; set; }
        public int NumeroLit { get; set; }
        public int IDMedecin { get; set; }
    
        public virtual Lit Lit { get; set; }
        public virtual Medecin Medecin { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
